apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: llama-cpp-python
spec:
  predictor:
    model:
      modelFormat:
        name: gguf
      runtime: llama-cpp-python-runtime
      storageUri: pvc://llama-cpp-python-claim/
